<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Price_price</name>
   <tag></tag>
   <elementGuidId>51d89846-4a26-43b7-8bff-594df4c13df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;price&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e27f23e2-3e7a-4ece-abc1-32c577679223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dea99ce7-7364-4920-ac21-9e7640661f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>a8a0c47b-464f-43ea-94c4-5535555c460e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container  my-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 mx-auto&quot;]/form[1]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-sm-8&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>91a54b74-402d-41e3-8874-47464d084a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>700</value>
      <webElementGuid>ac7f1691-3bda-42d3-b770-5f692897f026</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='price']</value>
      <webElementGuid>04e8a89c-af00-477e-b301-69f6063c4319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[5]/div/input</value>
      <webElementGuid>aa9ea189-5e02-4665-8329-ca009e821936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>deafc761-f413-4626-bd26-d41e8db25546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'price']</value>
      <webElementGuid>f832bd23-bbe1-4f37-9389-ed2feca80e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[4]/div/input</value>
      <webElementGuid>36373a4f-1960-459e-928e-c995dce54a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>9bf20afe-9f06-44a2-8e63-9d2935c33533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
