<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//tr[variavel]/td[2]</description>
   <name>campo-nome-xPath-comVariavel</name>
   <tag></tag>
   <elementGuidId>e5ccfd85-cac7-4154-8a3a-22987b000986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/table/tbody/tr[varCpoNome]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
