<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Por favor, preencha todos os campos</name>
   <tag></tag>
   <elementGuidId>83164513-970f-4e5d-906b-32a08dba067a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3613c3b0-3fc4-442f-8b2b-cd37bcd95d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>8e20c5c1-9f2b-4183-8bea-f4d3e6837639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger</value>
      <webElementGuid>6dd301c8-29c0-450d-bfbb-2d2b52b9a537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>b51fc5e0-3084-4e36-99e6-7df0d5641617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Por favor, preencha todos os campos</value>
      <webElementGuid>c90dd774-ae86-4351-8ca7-61d1798155a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert&quot;)</value>
      <webElementGuid>e0edf50e-5cea-4ada-96a9-04fd874e889a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='alert']</value>
      <webElementGuid>d6c749d3-16c4-4510-812a-e1e320b939b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div</value>
      <webElementGuid>8cef7dd4-ffea-496a-89db-bc48287431ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incluir Novo Produto'])[1]/following::div[3]</value>
      <webElementGuid>cf7a987c-ba59-4e0c-9f07-ef7654620236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produtos'])[1]/following::div[4]</value>
      <webElementGuid>5f16a251-5212-4b75-8065-b07aba6e4749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::div[1]</value>
      <webElementGuid>442a9b67-a217-4f59-b19e-8d821a4f9966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/preceding::div[3]</value>
      <webElementGuid>ca552243-ff6b-40d2-8840-934d21e0dfb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Por favor, preencha todos os campos']/parent::*</value>
      <webElementGuid>4bbb4762-0d65-4ecb-ab1e-4c206fb41cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>c8d0bc08-02eb-4d83-ab09-61b84b0c57dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'alert' and (text() = 'Por favor, preencha todos os campos' or . = 'Por favor, preencha todos os campos')]</value>
      <webElementGuid>60a7ac85-de66-47cf-86b7-2afacbbad9a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
